server:
  port: 5000
spring:
  application:
    name: boot-rabbitmq-study
  rabbitmq:
    host: 192.168.63.100
    port: 5672
    username: admin
    password: admin
    publisher-confirm-type: correlated
    publisher-returns: true